version: '3'

services:
  app:
    build: .
    platform: linux/x86_64
    container_name: gh-runner
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - ORGANIZATION=bigmikesolutions
      - RUNNER_GROUP=Development
      - RUNNER_NAME=michal-local-1
      - RUNNER_LABELS=development
      - ACCESS_TOKEN=${ACCESS_TOKEN}
