version: '3'

services:
  app:
    image: ghcr.io/actions-runner-controller/actions-runner-controller/actions-runner-dind:v2.321.0-ubuntu-20.04-8b36ea9
    container_name: gh-runner
    volumes:
      - runner-data:/runner
    privileged: true 
    environment:
      - RUNNER_GROUP=Development
      - RUNNER_NAME=michal-local-1
      - RUNNER_LABELS=development
      - RUNNER_ORG=bigmikesolutions
      - RUNNER_TOKEN=${ACCESS_TOKEN}

volumes:
  runner-data:
    driver: local