name: "Check whether new image fulfills all requirements"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  check_image:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:dind
        options: --privileged  

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Docker commands
        run: |
          docker info    
          docker run hello-world